install

diff --git a/bin/javaCheck b/bin/javaCheck
--- a/bin/javaCheck
+++ b/bin/javaCheck
@@ -4,8 +4,8 @@ set -o posix
 usage_exit() {
   echo "Usage: $0 [-i] [-r] [-p] [-l] [-k]" 1>&2
   echo "Check the versions of Java in Kibrary if exists, otherwise in PATH"
-#  echo "  -r $0 checks if the installed Java can run Kibrary and does not care about the Java compiler. If this option is not specified, $0 also checks if the installed Java compiler can compile Kibrary."
-  echo "  -i prints java and javac version in PATH."
+  echo "  -r $0 checks if the installed Java can run Kibrary and does not care about the Java compiler. If this option is not specified, $0 also checks if the installed Java compiler can compile Kibrary."
+  echo "  -i prints java and javac versions in PATH."
 #  echo "  -p prints or checks java and javac version in PATH even Kibrary has ones."
 #  echo "  -k prints or checks java and javac version in Kibrary, if there are none in Kibrary, always error exits."
 #  echo "  -l checks both java and javac not only can run Kibrary but are the latest. If -r option is specified, the version of javac is not checked."
@@ -16,6 +16,7 @@ if [ -z "$KIBRARY_HOME" ]; then
   printf "KIBRARY_HOME is not set.\n" 1>&2
   KIBRARY_HOME="$HOME/Kibrary"
   if [ ! -e "$KIBRARY_HOME" ]; then
+    printf "Assumed KIBRARY_HOME(%s) does not exist. (71)\n" "$KIBRARY_HOME" 
     exit 71
   fi
   printf "It is assumed to be %s.\n" "$KIBRARY_HOME" 1>&2
@@ -34,8 +35,8 @@ do
 done
 
 if [ -n "$FLG_K" ] && [ -n "$FLG_P" ]; then
-  echo " -k and -p can not be used simultaneously."
-  exit 1
+  echo " -k and -p can not be used simultaneously. (99)" 1>&2
+  exit 99
 fi
 
 if [ -e "$KIBRARY_HOME"/bin/.kibraryrc ]; then
@@ -47,19 +48,19 @@ if [ -e "$KIBRARY_HOME"/bin/.kibraryrc ]; then
     . "$KIBRARY_HOME"/bin/.kibraryrc -- || return 1
   fi
 else
-  printf "No file for variables. Please reinstall Kibrary.\\n" 1>&2
+  printf "No file for variables. Please reinstall Kibrary. (71)\n" 1>&2
   exit 71
 fi
 
 print_get_java(){
-  printf "Get the latest Java \\033[1;31m%s\\033[m from Oracle (https://www.oracle.com/technetwork/java/javase/downloads/index.html).\\n" "$latest_java8_version" 1>&2
+  printf "Get the latest Java \\033[1;31m%s\\033[m from Oracle (https://www.oracle.com/technetwork/java/javase/downloads/index.html).\n" "$latest_java8_version" 1>&2
   printf "If you want to install automatically, launch the script as below (copy and paste):\\n" 1>&2
-  printf "%s\\n" "$KIBRARY_BIN/javaInstall" 1>&2
+  printf "%s\n" "$KIBRARY_BIN/javaInstall" 1>&2
   return
 }
 
 print_set_java8(){
-  printf "Please set \$JAVA the latest Java 8 (\\033[1;31m%s\\033[m), if there's anything wrong. I will catch up soon.\\n" "$latest_java8_version"
+  printf "Please set \$JAVA the latest Java 8 (\\033[1;31m%s\\033[m), if there's anything wrong. I will catch up soon.\n" "$latest_java8_version"
   return
 }
 
@@ -67,7 +68,7 @@ print_set_java8(){
 if command -v "$JAVA" 1>/dev/null 2>&1; then
   java_version=$($JAVA -version 2>&1 | awk '/version/{gsub(/\x22/,"",$3);print $3}')
 else
-  printf "Java Runtime Environment is not found. (250)\\n"
+  printf "Java Runtime Environment is not found. (250)\n"
   exit 250
 fi
 
@@ -75,14 +76,14 @@ if command -v "$JAVAC" 1>/dev/null 2>&1; then
   javac_version=$($JAVAC -version 2>&1 | awk '{print $2}')
 #  javac_version_final_number=${javac_version#1.8.0_}
 elif [ -z "$FLG_R" ]; then
-  printf "Java compiler is not found. (255)\\n"
+  printf "Java compiler is not found. (255)\n"
   exit 255
 fi
 #echo "$javac_version"
 
 if [ -n "$FLG_I" ]; then
-  printf "java %s\\n" "$java_version"
-  printf "javac %s\\n" "$javac_version"
+  printf "java %s\n" "$java_version"
+  printf "javac %s\n" "$javac_version"
   exit 0
 fi
 
@@ -95,8 +96,8 @@ jsp='https://javadl-esd-secure.oracle.com/update/baseline.version'
 
 latest_version_list=\
 $(curl -s -L $jsp)
-latest_java12_version=$(echo "$latest_version_list" | grep '^12')
 latest_java13_version=$(echo "$latest_version_list" | grep '^13')
+latest_java12_version=$(echo "$latest_version_list" | grep '^12')
 latest_java11_version=$(echo "$latest_version_list" | grep '^11')
 latest_java10_version=$(echo "$latest_version_list" | grep '^10')
 latest_java9_version=$(echo "$latest_version_list" | grep '^9')
@@ -106,91 +107,72 @@ latest_java6_version=$(echo "$latest_version_list" | grep '^1\.6')
 latest_java5_version=$(echo "$latest_version_list" | grep '^1\.5')
 latest_java4_version=$(echo "$latest_version_list" | grep '^1\.4')
 
+printf "You use Java \\033[1;31m%s\\033[m.\n" "$java_version" 1>&2
+
 case "$java_version" in
 #Java 8
   1.8* )
-    printf "You use Java 8 (\\033[1;31m%s\\033[m).\\n" "$java_version"
     if [ "$latest_java8_version" = "$java_version" ] || [ "$latest_java8_version" \< "$java_version" ]; then
       exit 0
     else
-      printf "It's not latest. Please set \$JAVA \\033[1;31m%s\\033[m. (8)\\n" "$latest_java8_version"
+      printf "It's not latest. Please consider updating it to \\033[1;31m%s\\033[m. (8)\n" "$latest_java8_version" 1>&2
       exit 8
     fi
      ;;
 #Java 9
   9* )
-    printf "It's amaging that you use Java 9 (\\033[1;31m%s\\033[m)!\\n" "$java_version"
-    printf "I am sorry, however, a bit afraid of the compatibility.\\n"
-    printf "It is NOT an LTS release.\\n"
     if [ "$latest_java9_version" = "$java_version" ] || [ "$latest_java9_version" \< "$java_version" ]; then
-      printf "But.. anyway it's the latest Java 9.\\n"
       print_set_java8
       exit 0
     else
-      printf "It's not latest. Please set \$JAVA the latest Java 9. (9)\\n"
+      printf "It's not latest. Please consider updating it to \\033[1;31m%s\\033[m. (9)\n" "$latest_java9_version"
       exit 9
     fi
      ;;
 #Java 10 
   10* )
-    printf "It's amaging that you use Java 10 (\\033[1;31m%s\\033[m)!\\n" "$java_version"
-    printf "I am sorry, however, a bit afraid of the compatibility.\\n"
-    printf "It is NOT an LTS release.\\n"
     if [ "$latest_java10_version" = "$java_version" ] || [ "$latest_java10_version" \< "$java_version" ]; then
-      printf "But.. anyway it's the latest Java 10.\\n"
       print_set_java8
       exit 0
     else
-      printf "It's not latest. Please set \$JAVA the latest Java 10. (10)\\n"
+      printf "It's not latest. Please consider updating it to \\033[1;31m%s\\033[m. (10)\n" "$latest_java10_version"
       exit 10
     fi
     ;; 
 #Java 11
   11* )
-    printf "It's amaging that you use Java 11 (\\033[1;31m%s\\033[m) (LTS)!\\n" "$java_version"
-    printf "I am sorry, however, a bit afraid of the compatibility.\\n"
     if [ "$latest_java11_version" = "$java_version" ] || [ "$latest_java11_version" \< "$java_version" ]; then
-      printf "But.. anyway it's the latest Java 11.\\n"
       print_set_java8
       exit 0
     else
-      printf "\\033[4mIn addtion\\e[m, its version \\033[1;31m%s\\033[m may not be the latest \\033[1;31m%s\\033[m.\\n" "$java_version" "$latest_java11_version"
-      printf "It's not latest. Please set \$JAVA the latest Java 11. (11)\\n"
+      printf "It's not latest. Please consider updating it to \\033[1;31m%s\\033[m. (11)\n" "$latest_java11_version"  
       exit 11
     fi      
     ;;
 #Java 12
   12* )
-    printf "It's amaging that you use Java 12 (\\033[1;31m%s\\033[m)!\\n" "$java_version"
-    printf "I am sorry, however, a bit afraid of the compatibility.\\n"
     if [ "$latest_java12_version" = "$java_version" ] || [ "$latest_java12_version" \< "$java_version" ]; then
-      printf "But.. anyway it's the latest Java 12.\\n"
       print_set_java8
       exit 0
     else
-      printf "\\033[4mIn addtion\\e[m, its version \\033[1;31m%s\\033[m may not be the latest \\033[1;31m%s\\033[m.\\n" "$java_version" "$latest_java12_version"
-      printf "It's not latest. Please set \$JAVA the latest Java 12. (12)\\n"
+      printf "It's not latest. Please consider updating it to \\033[1;31m%s\\033[m. (12)\n" "$latest_java12_version"  
       exit 12
     fi      
     ;;
 #Java 13
   13* )
-    printf "It's amaging that you use Java 13 (\\033[1;31m%s\\033[m)!\\n" "$java_version"
-    printf "I am sorry, however, a bit afraid of the compatibility.\\n"
     if [ "$latest_java13_version" = "$java_version" ] || [ "$latest_java13_version" \< "$java_version" ]; then
-      printf "But.. anyway it's the latest Java 13.\\n"
       print_set_java8
       exit 0
     else
-      printf "\\033[4mIn addtion\\e[m, its version \\033[1;31m%s\\033[m may not be the latest \\033[1;31m%s\\033[m.\\n" "$java_version" "$latest_java13_version"
-      printf "It's not latest. Please set \$JAVA the latest Java 13. (13)\\n"
+      printf "It's not latest. Please consider updating it to \\033[1;31m%s\\033[m. (13)\n" "$latest_java13_version"
       exit 13
     fi      
     ;;
   * )
-    printf "Installed Java version is \\033[1;31m%s\\033[m. You need \\033[4mJava 8\\033[m.\\n" "$java_version"
+    printf "Installed Java version is \\033[1;31m%s\\033[m. You need \\033[4mJava 8\\033[m or later. (26)\\n" "$java_version"
     print_get_java
-    exit 255
+    exit 26
     ;;
 esac
 
